#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MediaAndroidTest.Resource", IsApplication=true)]

namespace MediaAndroidTest
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Plugin.Media.Resource.Attribute.alpha = global::MediaAndroidTest.Resource.Attribute.alpha;
			global::Plugin.Media.Resource.Attribute.coordinatorLayoutStyle = global::MediaAndroidTest.Resource.Attribute.coordinatorLayoutStyle;
			global::Plugin.Media.Resource.Attribute.font = global::MediaAndroidTest.Resource.Attribute.font;
			global::Plugin.Media.Resource.Attribute.fontProviderAuthority = global::MediaAndroidTest.Resource.Attribute.fontProviderAuthority;
			global::Plugin.Media.Resource.Attribute.fontProviderCerts = global::MediaAndroidTest.Resource.Attribute.fontProviderCerts;
			global::Plugin.Media.Resource.Attribute.fontProviderFetchStrategy = global::MediaAndroidTest.Resource.Attribute.fontProviderFetchStrategy;
			global::Plugin.Media.Resource.Attribute.fontProviderFetchTimeout = global::MediaAndroidTest.Resource.Attribute.fontProviderFetchTimeout;
			global::Plugin.Media.Resource.Attribute.fontProviderPackage = global::MediaAndroidTest.Resource.Attribute.fontProviderPackage;
			global::Plugin.Media.Resource.Attribute.fontProviderQuery = global::MediaAndroidTest.Resource.Attribute.fontProviderQuery;
			global::Plugin.Media.Resource.Attribute.fontStyle = global::MediaAndroidTest.Resource.Attribute.fontStyle;
			global::Plugin.Media.Resource.Attribute.fontVariationSettings = global::MediaAndroidTest.Resource.Attribute.fontVariationSettings;
			global::Plugin.Media.Resource.Attribute.fontWeight = global::MediaAndroidTest.Resource.Attribute.fontWeight;
			global::Plugin.Media.Resource.Attribute.keylines = global::MediaAndroidTest.Resource.Attribute.keylines;
			global::Plugin.Media.Resource.Attribute.layout_anchor = global::MediaAndroidTest.Resource.Attribute.layout_anchor;
			global::Plugin.Media.Resource.Attribute.layout_anchorGravity = global::MediaAndroidTest.Resource.Attribute.layout_anchorGravity;
			global::Plugin.Media.Resource.Attribute.layout_behavior = global::MediaAndroidTest.Resource.Attribute.layout_behavior;
			global::Plugin.Media.Resource.Attribute.layout_dodgeInsetEdges = global::MediaAndroidTest.Resource.Attribute.layout_dodgeInsetEdges;
			global::Plugin.Media.Resource.Attribute.layout_insetEdge = global::MediaAndroidTest.Resource.Attribute.layout_insetEdge;
			global::Plugin.Media.Resource.Attribute.layout_keyline = global::MediaAndroidTest.Resource.Attribute.layout_keyline;
			global::Plugin.Media.Resource.Attribute.statusBarBackground = global::MediaAndroidTest.Resource.Attribute.statusBarBackground;
			global::Plugin.Media.Resource.Attribute.ttcIndex = global::MediaAndroidTest.Resource.Attribute.ttcIndex;
			global::Plugin.Media.Resource.Color.notification_action_color_filter = global::MediaAndroidTest.Resource.Color.notification_action_color_filter;
			global::Plugin.Media.Resource.Color.notification_icon_bg_color = global::MediaAndroidTest.Resource.Color.notification_icon_bg_color;
			global::Plugin.Media.Resource.Color.ripple_material_light = global::MediaAndroidTest.Resource.Color.ripple_material_light;
			global::Plugin.Media.Resource.Color.secondary_text_default_material_light = global::MediaAndroidTest.Resource.Color.secondary_text_default_material_light;
			global::Plugin.Media.Resource.Dimension.compat_button_inset_horizontal_material = global::MediaAndroidTest.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Plugin.Media.Resource.Dimension.compat_button_inset_vertical_material = global::MediaAndroidTest.Resource.Dimension.compat_button_inset_vertical_material;
			global::Plugin.Media.Resource.Dimension.compat_button_padding_horizontal_material = global::MediaAndroidTest.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Plugin.Media.Resource.Dimension.compat_button_padding_vertical_material = global::MediaAndroidTest.Resource.Dimension.compat_button_padding_vertical_material;
			global::Plugin.Media.Resource.Dimension.compat_control_corner_material = global::MediaAndroidTest.Resource.Dimension.compat_control_corner_material;
			global::Plugin.Media.Resource.Dimension.compat_notification_large_icon_max_height = global::MediaAndroidTest.Resource.Dimension.compat_notification_large_icon_max_height;
			global::Plugin.Media.Resource.Dimension.compat_notification_large_icon_max_width = global::MediaAndroidTest.Resource.Dimension.compat_notification_large_icon_max_width;
			global::Plugin.Media.Resource.Dimension.notification_action_icon_size = global::MediaAndroidTest.Resource.Dimension.notification_action_icon_size;
			global::Plugin.Media.Resource.Dimension.notification_action_text_size = global::MediaAndroidTest.Resource.Dimension.notification_action_text_size;
			global::Plugin.Media.Resource.Dimension.notification_big_circle_margin = global::MediaAndroidTest.Resource.Dimension.notification_big_circle_margin;
			global::Plugin.Media.Resource.Dimension.notification_content_margin_start = global::MediaAndroidTest.Resource.Dimension.notification_content_margin_start;
			global::Plugin.Media.Resource.Dimension.notification_large_icon_height = global::MediaAndroidTest.Resource.Dimension.notification_large_icon_height;
			global::Plugin.Media.Resource.Dimension.notification_large_icon_width = global::MediaAndroidTest.Resource.Dimension.notification_large_icon_width;
			global::Plugin.Media.Resource.Dimension.notification_main_column_padding_top = global::MediaAndroidTest.Resource.Dimension.notification_main_column_padding_top;
			global::Plugin.Media.Resource.Dimension.notification_media_narrow_margin = global::MediaAndroidTest.Resource.Dimension.notification_media_narrow_margin;
			global::Plugin.Media.Resource.Dimension.notification_right_icon_size = global::MediaAndroidTest.Resource.Dimension.notification_right_icon_size;
			global::Plugin.Media.Resource.Dimension.notification_right_side_padding_top = global::MediaAndroidTest.Resource.Dimension.notification_right_side_padding_top;
			global::Plugin.Media.Resource.Dimension.notification_small_icon_background_padding = global::MediaAndroidTest.Resource.Dimension.notification_small_icon_background_padding;
			global::Plugin.Media.Resource.Dimension.notification_small_icon_size_as_large = global::MediaAndroidTest.Resource.Dimension.notification_small_icon_size_as_large;
			global::Plugin.Media.Resource.Dimension.notification_subtext_size = global::MediaAndroidTest.Resource.Dimension.notification_subtext_size;
			global::Plugin.Media.Resource.Dimension.notification_top_pad = global::MediaAndroidTest.Resource.Dimension.notification_top_pad;
			global::Plugin.Media.Resource.Dimension.notification_top_pad_large_text = global::MediaAndroidTest.Resource.Dimension.notification_top_pad_large_text;
			global::Plugin.Media.Resource.Drawable.notification_action_background = global::MediaAndroidTest.Resource.Drawable.notification_action_background;
			global::Plugin.Media.Resource.Drawable.notification_bg = global::MediaAndroidTest.Resource.Drawable.notification_bg;
			global::Plugin.Media.Resource.Drawable.notification_bg_low = global::MediaAndroidTest.Resource.Drawable.notification_bg_low;
			global::Plugin.Media.Resource.Drawable.notification_bg_low_normal = global::MediaAndroidTest.Resource.Drawable.notification_bg_low_normal;
			global::Plugin.Media.Resource.Drawable.notification_bg_low_pressed = global::MediaAndroidTest.Resource.Drawable.notification_bg_low_pressed;
			global::Plugin.Media.Resource.Drawable.notification_bg_normal = global::MediaAndroidTest.Resource.Drawable.notification_bg_normal;
			global::Plugin.Media.Resource.Drawable.notification_bg_normal_pressed = global::MediaAndroidTest.Resource.Drawable.notification_bg_normal_pressed;
			global::Plugin.Media.Resource.Drawable.notification_icon_background = global::MediaAndroidTest.Resource.Drawable.notification_icon_background;
			global::Plugin.Media.Resource.Drawable.notification_template_icon_bg = global::MediaAndroidTest.Resource.Drawable.notification_template_icon_bg;
			global::Plugin.Media.Resource.Drawable.notification_template_icon_low_bg = global::MediaAndroidTest.Resource.Drawable.notification_template_icon_low_bg;
			global::Plugin.Media.Resource.Drawable.notification_tile_bg = global::MediaAndroidTest.Resource.Drawable.notification_tile_bg;
			global::Plugin.Media.Resource.Drawable.notify_panel_notification_icon_bg = global::MediaAndroidTest.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Plugin.Media.Resource.Id.actions = global::MediaAndroidTest.Resource.Id.actions;
			global::Plugin.Media.Resource.Id.action_container = global::MediaAndroidTest.Resource.Id.action_container;
			global::Plugin.Media.Resource.Id.action_divider = global::MediaAndroidTest.Resource.Id.action_divider;
			global::Plugin.Media.Resource.Id.action_image = global::MediaAndroidTest.Resource.Id.action_image;
			global::Plugin.Media.Resource.Id.action_text = global::MediaAndroidTest.Resource.Id.action_text;
			global::Plugin.Media.Resource.Id.all = global::MediaAndroidTest.Resource.Id.all;
			global::Plugin.Media.Resource.Id.async = global::MediaAndroidTest.Resource.Id.async;
			global::Plugin.Media.Resource.Id.blocking = global::MediaAndroidTest.Resource.Id.blocking;
			global::Plugin.Media.Resource.Id.bottom = global::MediaAndroidTest.Resource.Id.bottom;
			global::Plugin.Media.Resource.Id.center = global::MediaAndroidTest.Resource.Id.center;
			global::Plugin.Media.Resource.Id.center_horizontal = global::MediaAndroidTest.Resource.Id.center_horizontal;
			global::Plugin.Media.Resource.Id.center_vertical = global::MediaAndroidTest.Resource.Id.center_vertical;
			global::Plugin.Media.Resource.Id.chronometer = global::MediaAndroidTest.Resource.Id.chronometer;
			global::Plugin.Media.Resource.Id.clip_horizontal = global::MediaAndroidTest.Resource.Id.clip_horizontal;
			global::Plugin.Media.Resource.Id.clip_vertical = global::MediaAndroidTest.Resource.Id.clip_vertical;
			global::Plugin.Media.Resource.Id.end = global::MediaAndroidTest.Resource.Id.end;
			global::Plugin.Media.Resource.Id.fill = global::MediaAndroidTest.Resource.Id.fill;
			global::Plugin.Media.Resource.Id.fill_horizontal = global::MediaAndroidTest.Resource.Id.fill_horizontal;
			global::Plugin.Media.Resource.Id.fill_vertical = global::MediaAndroidTest.Resource.Id.fill_vertical;
			global::Plugin.Media.Resource.Id.forever = global::MediaAndroidTest.Resource.Id.forever;
			global::Plugin.Media.Resource.Id.icon = global::MediaAndroidTest.Resource.Id.icon;
			global::Plugin.Media.Resource.Id.icon_group = global::MediaAndroidTest.Resource.Id.icon_group;
			global::Plugin.Media.Resource.Id.info = global::MediaAndroidTest.Resource.Id.info;
			global::Plugin.Media.Resource.Id.italic = global::MediaAndroidTest.Resource.Id.italic;
			global::Plugin.Media.Resource.Id.left = global::MediaAndroidTest.Resource.Id.left;
			global::Plugin.Media.Resource.Id.line1 = global::MediaAndroidTest.Resource.Id.line1;
			global::Plugin.Media.Resource.Id.line3 = global::MediaAndroidTest.Resource.Id.line3;
			global::Plugin.Media.Resource.Id.none = global::MediaAndroidTest.Resource.Id.none;
			global::Plugin.Media.Resource.Id.normal = global::MediaAndroidTest.Resource.Id.normal;
			global::Plugin.Media.Resource.Id.notification_background = global::MediaAndroidTest.Resource.Id.notification_background;
			global::Plugin.Media.Resource.Id.notification_main_column = global::MediaAndroidTest.Resource.Id.notification_main_column;
			global::Plugin.Media.Resource.Id.notification_main_column_container = global::MediaAndroidTest.Resource.Id.notification_main_column_container;
			global::Plugin.Media.Resource.Id.right = global::MediaAndroidTest.Resource.Id.right;
			global::Plugin.Media.Resource.Id.right_icon = global::MediaAndroidTest.Resource.Id.right_icon;
			global::Plugin.Media.Resource.Id.right_side = global::MediaAndroidTest.Resource.Id.right_side;
			global::Plugin.Media.Resource.Id.start = global::MediaAndroidTest.Resource.Id.start;
			global::Plugin.Media.Resource.Id.tag_transition_group = global::MediaAndroidTest.Resource.Id.tag_transition_group;
			global::Plugin.Media.Resource.Id.tag_unhandled_key_event_manager = global::MediaAndroidTest.Resource.Id.tag_unhandled_key_event_manager;
			global::Plugin.Media.Resource.Id.tag_unhandled_key_listeners = global::MediaAndroidTest.Resource.Id.tag_unhandled_key_listeners;
			global::Plugin.Media.Resource.Id.text = global::MediaAndroidTest.Resource.Id.text;
			global::Plugin.Media.Resource.Id.text2 = global::MediaAndroidTest.Resource.Id.text2;
			global::Plugin.Media.Resource.Id.time = global::MediaAndroidTest.Resource.Id.time;
			global::Plugin.Media.Resource.Id.title = global::MediaAndroidTest.Resource.Id.title;
			global::Plugin.Media.Resource.Id.top = global::MediaAndroidTest.Resource.Id.top;
			global::Plugin.Media.Resource.Integer.status_bar_notification_info_maxnum = global::MediaAndroidTest.Resource.Integer.status_bar_notification_info_maxnum;
			global::Plugin.Media.Resource.Layout.notification_action = global::MediaAndroidTest.Resource.Layout.notification_action;
			global::Plugin.Media.Resource.Layout.notification_action_tombstone = global::MediaAndroidTest.Resource.Layout.notification_action_tombstone;
			global::Plugin.Media.Resource.Layout.notification_template_custom_big = global::MediaAndroidTest.Resource.Layout.notification_template_custom_big;
			global::Plugin.Media.Resource.Layout.notification_template_icon_group = global::MediaAndroidTest.Resource.Layout.notification_template_icon_group;
			global::Plugin.Media.Resource.Layout.notification_template_part_chronometer = global::MediaAndroidTest.Resource.Layout.notification_template_part_chronometer;
			global::Plugin.Media.Resource.Layout.notification_template_part_time = global::MediaAndroidTest.Resource.Layout.notification_template_part_time;
			global::Plugin.Media.Resource.String.status_bar_notification_info_overflow = global::MediaAndroidTest.Resource.String.status_bar_notification_info_overflow;
			global::Plugin.Media.Resource.Style.TextAppearance_Compat_Notification = global::MediaAndroidTest.Resource.Style.TextAppearance_Compat_Notification;
			global::Plugin.Media.Resource.Style.TextAppearance_Compat_Notification_Info = global::MediaAndroidTest.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Plugin.Media.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::MediaAndroidTest.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Plugin.Media.Resource.Style.TextAppearance_Compat_Notification_Time = global::MediaAndroidTest.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Plugin.Media.Resource.Style.TextAppearance_Compat_Notification_Title = global::MediaAndroidTest.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Plugin.Media.Resource.Style.Widget_Compat_NotificationActionContainer = global::MediaAndroidTest.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Plugin.Media.Resource.Style.Widget_Compat_NotificationActionText = global::MediaAndroidTest.Resource.Style.Widget_Compat_NotificationActionText;
			global::Plugin.Media.Resource.Style.Widget_Support_CoordinatorLayout = global::MediaAndroidTest.Resource.Style.Widget_Support_CoordinatorLayout;
			global::Plugin.Media.Resource.Styleable.ColorStateListItem = global::MediaAndroidTest.Resource.Styleable.ColorStateListItem;
			global::Plugin.Media.Resource.Styleable.ColorStateListItem_alpha = global::MediaAndroidTest.Resource.Styleable.ColorStateListItem_alpha;
			global::Plugin.Media.Resource.Styleable.ColorStateListItem_android_alpha = global::MediaAndroidTest.Resource.Styleable.ColorStateListItem_android_alpha;
			global::Plugin.Media.Resource.Styleable.ColorStateListItem_android_color = global::MediaAndroidTest.Resource.Styleable.ColorStateListItem_android_color;
			global::Plugin.Media.Resource.Styleable.CoordinatorLayout = global::MediaAndroidTest.Resource.Styleable.CoordinatorLayout;
			global::Plugin.Media.Resource.Styleable.CoordinatorLayout_keylines = global::MediaAndroidTest.Resource.Styleable.CoordinatorLayout_keylines;
			global::Plugin.Media.Resource.Styleable.CoordinatorLayout_Layout = global::MediaAndroidTest.Resource.Styleable.CoordinatorLayout_Layout;
			global::Plugin.Media.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity = global::MediaAndroidTest.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity;
			global::Plugin.Media.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor = global::MediaAndroidTest.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor;
			global::Plugin.Media.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity = global::MediaAndroidTest.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity;
			global::Plugin.Media.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior = global::MediaAndroidTest.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior;
			global::Plugin.Media.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges = global::MediaAndroidTest.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges;
			global::Plugin.Media.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge = global::MediaAndroidTest.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge;
			global::Plugin.Media.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline = global::MediaAndroidTest.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline;
			global::Plugin.Media.Resource.Styleable.CoordinatorLayout_statusBarBackground = global::MediaAndroidTest.Resource.Styleable.CoordinatorLayout_statusBarBackground;
			global::Plugin.Media.Resource.Styleable.FontFamily = global::MediaAndroidTest.Resource.Styleable.FontFamily;
			global::Plugin.Media.Resource.Styleable.FontFamilyFont = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont;
			global::Plugin.Media.Resource.Styleable.FontFamilyFont_android_font = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_android_font;
			global::Plugin.Media.Resource.Styleable.FontFamilyFont_android_fontStyle = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Plugin.Media.Resource.Styleable.FontFamilyFont_android_fontVariationSettings = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_android_fontVariationSettings;
			global::Plugin.Media.Resource.Styleable.FontFamilyFont_android_fontWeight = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Plugin.Media.Resource.Styleable.FontFamilyFont_android_ttcIndex = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_android_ttcIndex;
			global::Plugin.Media.Resource.Styleable.FontFamilyFont_font = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_font;
			global::Plugin.Media.Resource.Styleable.FontFamilyFont_fontStyle = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Plugin.Media.Resource.Styleable.FontFamilyFont_fontVariationSettings = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_fontVariationSettings;
			global::Plugin.Media.Resource.Styleable.FontFamilyFont_fontWeight = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_fontWeight;
			global::Plugin.Media.Resource.Styleable.FontFamilyFont_ttcIndex = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_ttcIndex;
			global::Plugin.Media.Resource.Styleable.FontFamily_fontProviderAuthority = global::MediaAndroidTest.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Plugin.Media.Resource.Styleable.FontFamily_fontProviderCerts = global::MediaAndroidTest.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Plugin.Media.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::MediaAndroidTest.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Plugin.Media.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::MediaAndroidTest.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Plugin.Media.Resource.Styleable.FontFamily_fontProviderPackage = global::MediaAndroidTest.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Plugin.Media.Resource.Styleable.FontFamily_fontProviderQuery = global::MediaAndroidTest.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Plugin.Media.Resource.Styleable.GradientColor = global::MediaAndroidTest.Resource.Styleable.GradientColor;
			global::Plugin.Media.Resource.Styleable.GradientColorItem = global::MediaAndroidTest.Resource.Styleable.GradientColorItem;
			global::Plugin.Media.Resource.Styleable.GradientColorItem_android_color = global::MediaAndroidTest.Resource.Styleable.GradientColorItem_android_color;
			global::Plugin.Media.Resource.Styleable.GradientColorItem_android_offset = global::MediaAndroidTest.Resource.Styleable.GradientColorItem_android_offset;
			global::Plugin.Media.Resource.Styleable.GradientColor_android_centerColor = global::MediaAndroidTest.Resource.Styleable.GradientColor_android_centerColor;
			global::Plugin.Media.Resource.Styleable.GradientColor_android_centerX = global::MediaAndroidTest.Resource.Styleable.GradientColor_android_centerX;
			global::Plugin.Media.Resource.Styleable.GradientColor_android_centerY = global::MediaAndroidTest.Resource.Styleable.GradientColor_android_centerY;
			global::Plugin.Media.Resource.Styleable.GradientColor_android_endColor = global::MediaAndroidTest.Resource.Styleable.GradientColor_android_endColor;
			global::Plugin.Media.Resource.Styleable.GradientColor_android_endX = global::MediaAndroidTest.Resource.Styleable.GradientColor_android_endX;
			global::Plugin.Media.Resource.Styleable.GradientColor_android_endY = global::MediaAndroidTest.Resource.Styleable.GradientColor_android_endY;
			global::Plugin.Media.Resource.Styleable.GradientColor_android_gradientRadius = global::MediaAndroidTest.Resource.Styleable.GradientColor_android_gradientRadius;
			global::Plugin.Media.Resource.Styleable.GradientColor_android_startColor = global::MediaAndroidTest.Resource.Styleable.GradientColor_android_startColor;
			global::Plugin.Media.Resource.Styleable.GradientColor_android_startX = global::MediaAndroidTest.Resource.Styleable.GradientColor_android_startX;
			global::Plugin.Media.Resource.Styleable.GradientColor_android_startY = global::MediaAndroidTest.Resource.Styleable.GradientColor_android_startY;
			global::Plugin.Media.Resource.Styleable.GradientColor_android_tileMode = global::MediaAndroidTest.Resource.Styleable.GradientColor_android_tileMode;
			global::Plugin.Media.Resource.Styleable.GradientColor_android_type = global::MediaAndroidTest.Resource.Styleable.GradientColor_android_type;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int alpha = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int coordinatorLayoutStyle = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int font = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int fontProviderAuthority = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int fontProviderCerts = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int fontProviderFetchStrategy = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int fontProviderFetchTimeout = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int fontProviderPackage = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int fontProviderQuery = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int fontStyle = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int fontVariationSettings = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int fontWeight = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int keylines = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int layout_anchor = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int layout_anchorGravity = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int layout_behavior = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int layout_dodgeInsetEdges = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int layout_insetEdge = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int layout_keyline = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int statusBarBackground = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int ttcIndex = 2130771988;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int notification_action_color_filter = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int notification_icon_bg_color = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int ripple_material_light = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int secondary_text_default_material_light = 2130837507;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int compat_button_inset_horizontal_material = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int compat_button_inset_vertical_material = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int compat_button_padding_horizontal_material = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int compat_button_padding_vertical_material = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int compat_control_corner_material = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int compat_notification_large_icon_max_height = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int compat_notification_large_icon_max_width = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int notification_action_icon_size = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int notification_action_text_size = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int notification_big_circle_margin = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int notification_content_margin_start = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int notification_large_icon_height = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int notification_large_icon_width = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int notification_main_column_padding_top = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int notification_media_narrow_margin = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int notification_right_icon_size = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int notification_right_side_padding_top = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int notification_small_icon_background_padding = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int notification_small_icon_size_as_large = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int notification_subtext_size = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int notification_top_pad = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int notification_top_pad_large_text = 2130903061;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int Icon = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int notification_action_background = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int notification_bg = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int notification_bg_low = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int notification_bg_low_normal = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int notification_bg_low_pressed = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int notification_bg_normal = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int notification_bg_normal_pressed = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int notification_icon_background = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int notification_template_icon_bg = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int notification_template_icon_low_bg = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int notification_tile_bg = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int notify_panel_notification_icon_bg = 2130968588;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050005
			public const int actions = 2131034117;
			
			// aapt resource value: 0x7F050001
			public const int action_container = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int action_divider = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int action_image = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int action_text = 2131034116;
			
			// aapt resource value: 0x7F050006
			public const int all = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int async = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int blocking = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int bottom = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int button1 = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int button2 = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int button3 = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int center = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int center_horizontal = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int center_vertical = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int chronometer = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int clip_horizontal = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int clip_vertical = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int end = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int fill = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int fill_horizontal = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int fill_vertical = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int forever = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int icon = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int icon_group = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int imageView1 = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int info = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int italic = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int left = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int line1 = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int line3 = 2131034143;
			
			// aapt resource value: 0x7F050000
			public const int MyButton = 2131034112;
			
			// aapt resource value: 0x7F050020
			public const int none = 2131034144;
			
			// aapt resource value: 0x7F050021
			public const int normal = 2131034145;
			
			// aapt resource value: 0x7F050022
			public const int notification_background = 2131034146;
			
			// aapt resource value: 0x7F050023
			public const int notification_main_column = 2131034147;
			
			// aapt resource value: 0x7F050024
			public const int notification_main_column_container = 2131034148;
			
			// aapt resource value: 0x7F050025
			public const int right = 2131034149;
			
			// aapt resource value: 0x7F050026
			public const int right_icon = 2131034150;
			
			// aapt resource value: 0x7F050027
			public const int right_side = 2131034151;
			
			// aapt resource value: 0x7F050028
			public const int start = 2131034152;
			
			// aapt resource value: 0x7F050029
			public const int switch_save_album = 2131034153;
			
			// aapt resource value: 0x7F05002A
			public const int switch_size = 2131034154;
			
			// aapt resource value: 0x7F05002B
			public const int tag_transition_group = 2131034155;
			
			// aapt resource value: 0x7F05002C
			public const int tag_unhandled_key_event_manager = 2131034156;
			
			// aapt resource value: 0x7F05002D
			public const int tag_unhandled_key_listeners = 2131034157;
			
			// aapt resource value: 0x7F05002E
			public const int text = 2131034158;
			
			// aapt resource value: 0x7F05002F
			public const int text2 = 2131034159;
			
			// aapt resource value: 0x7F050030
			public const int time = 2131034160;
			
			// aapt resource value: 0x7F050031
			public const int title = 2131034161;
			
			// aapt resource value: 0x7F050032
			public const int top = 2131034162;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F060000
			public const int status_bar_notification_info_maxnum = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F070000
			public const int Main = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int notification_action = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int notification_action_tombstone = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int notification_template_custom_big = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int notification_template_icon_group = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int notification_template_part_chronometer = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int notification_template_part_time = 2131165190;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int ApplicationName = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int Hello = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int status_bar_notification_info_overflow = 2131230722;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int TextAppearance_Compat_Notification = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int TextAppearance_Compat_Notification_Info = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int TextAppearance_Compat_Notification_Line2 = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int TextAppearance_Compat_Notification_Time = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int TextAppearance_Compat_Notification_Title = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int Widget_Compat_NotificationActionContainer = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int Widget_Compat_NotificationActionText = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int Widget_Support_CoordinatorLayout = 2131296263;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x10101A5,0x101031F,0x7F010000 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771968};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			// aapt resource value: { 0x7F01000C,0x7F010013 }
			public static int[] CoordinatorLayout = new int[] {
					2130771980,
					2130771987};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: { 0x10100B3,0x7F01000D,0x7F01000E,0x7F01000F,0x7F010010,0x7F010011,0x7F010012 }
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_anchor = 1;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 2;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_behavior = 3;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 4;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_keyline = 6;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			// aapt resource value: { 0x7F010003,0x7F010004,0x7F010005,0x7F010006,0x7F010007,0x7F010008 }
			public static int[] FontFamily = new int[] {
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F010002,0x7F010009,0x7F01000A,0x7F01000B,0x7F010014 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771970,
					2130771977,
					2130771978,
					2130771979,
					2130771988};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0B0000
			public const int file_paths = 2131427328;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
